/*
 * Generated by dtrace(1M).
 */

#ifndef	_TRACE_H
#define	_TRACE_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define HASKELL_STABILITY "___dtrace_stability$haskell$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define HASKELL_TYPEDEFS "___dtrace_typedefs$haskell$v1"

#define	HASKELL_USER_TRACE(arg0) \
{ \
	__asm__ volatile(".reference " HASKELL_TYPEDEFS); \
	__dtrace_probe$haskell$user__trace$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " HASKELL_STABILITY); \
} 
#define	HASKELL_USER_TRACE_ENABLED() \
	__dtrace_isenabled$haskell$user__trace$v1()


extern void __dtrace_probe$haskell$user__trace$v1$63686172202a(char *);
extern int __dtrace_isenabled$haskell$user__trace$v1(void);

#ifdef	__cplusplus
}
#endif

#endif	/* _TRACE_H */
